FROM python:3.11-slim

WORKDIR /app

# Копируем зависимости
COPY backend/requirements.txt .

# Устанавливаем
RUN pip install --no-cache-dir -r requirements.txt

# Копируем весь код backend
COPY backend/ .

# Порт для Railway
EXPOSE 8000

# Запуск
CMD ["python", "run.py"]